import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

import { AuthProvider } from "~/app/_components/AuthProvider";
import { Navbar } from "~/app/_components/Navbar";
import { TopBar } from "~/app/_components/TopBar";
import { LanguageProvider } from "~/app/_components/LanguageContext";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body
        className="bg-bg-primary text-text-primary min-h-screen"
        suppressHydrationWarning
      >
        <LanguageProvider>
          <TRPCReactProvider>
            <AuthProvider>
              <div className="flex h-screen overflow-hidden bg-[#F8FAFC]">
                <Navbar />
                <div className="flex-1 flex flex-col min-w-0 h-full">
                  <TopBar />
                  <main className="flex-1 overflow-y-auto">{children}</main>
                </div>
              </div>
            </AuthProvider>
          </TRPCReactProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
