import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

import { AuthProvider } from "~/app/_components/AuthProvider";
import { AppLayout } from "~/app/_components/AppLayout";
import { LanguageProvider } from "~/app/_components/LanguageContext";
import { MobileNavProvider } from "~/app/_components/MobileNavContext";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja" className={`${geist.variable}`} suppressHydrationWarning>
      <body
        className="bg-bg-primary text-text-primary min-h-screen"
        suppressHydrationWarning
      >
        <LanguageProvider>
          <TRPCReactProvider>
            <AuthProvider>
              <MobileNavProvider>
                <AppLayout>{children}</AppLayout>
              </MobileNavProvider>
            </AuthProvider>
          </TRPCReactProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
